services:
- type: web
  name: minio
  healthCheckPath: /minio/health/live
  env: docker
  dockerfilePath: ./Dockerfile
  dockerContext: .
  autoDeploy: false
  disk:
    name: data
    mountPath: /data
    sizeGB: 1000
  envVars:
  - key: MINIO_ROOT_USER
    generateValue: true
  - key: MINIO_ROOT_PASSWORD
    generateValue: true
  - key: PORT
    value: 10000
